/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ApplicationUserService } from "../applicationUser.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ApplicationUserCreateInput } from "./ApplicationUserCreateInput";
import { ApplicationUser } from "./ApplicationUser";
import { ApplicationUserFindManyArgs } from "./ApplicationUserFindManyArgs";
import { ApplicationUserWhereUniqueInput } from "./ApplicationUserWhereUniqueInput";
import { ApplicationUserUpdateInput } from "./ApplicationUserUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ApplicationUserControllerBase {
  constructor(
    protected readonly service: ApplicationUserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ApplicationUser })
  @nestAccessControl.UseRoles({
    resource: "ApplicationUser",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createApplicationUser(
    @common.Body() data: ApplicationUserCreateInput
  ): Promise<ApplicationUser> {
    return await this.service.createApplicationUser({
      data: {
        ...data,

        oAuth: data.oAuth
          ? {
              connect: data.oAuth,
            }
          : undefined,

        role: data.role
          ? {
              connect: data.role,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,

        oAuth: {
          select: {
            id: true,
          },
        },

        password: true,

        role: {
          select: {
            id: true,
          },
        },

        supertokensId: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ApplicationUser] })
  @ApiNestedQuery(ApplicationUserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ApplicationUser",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async applicationUsers(
    @common.Req() request: Request
  ): Promise<ApplicationUser[]> {
    const args = plainToClass(ApplicationUserFindManyArgs, request.query);
    return this.service.applicationUsers({
      ...args,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,

        oAuth: {
          select: {
            id: true,
          },
        },

        password: true,

        role: {
          select: {
            id: true,
          },
        },

        supertokensId: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ApplicationUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApplicationUser",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async applicationUser(
    @common.Param() params: ApplicationUserWhereUniqueInput
  ): Promise<ApplicationUser | null> {
    const result = await this.service.applicationUser({
      where: params,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,

        oAuth: {
          select: {
            id: true,
          },
        },

        password: true,

        role: {
          select: {
            id: true,
          },
        },

        supertokensId: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ApplicationUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApplicationUser",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateApplicationUser(
    @common.Param() params: ApplicationUserWhereUniqueInput,
    @common.Body() data: ApplicationUserUpdateInput
  ): Promise<ApplicationUser | null> {
    try {
      return await this.service.updateApplicationUser({
        where: params,
        data: {
          ...data,

          oAuth: data.oAuth
            ? {
                connect: data.oAuth,
              }
            : undefined,

          role: data.role
            ? {
                connect: data.role,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,

          oAuth: {
            select: {
              id: true,
            },
          },

          password: true,

          role: {
            select: {
              id: true,
            },
          },

          supertokensId: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ApplicationUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApplicationUser",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteApplicationUser(
    @common.Param() params: ApplicationUserWhereUniqueInput
  ): Promise<ApplicationUser | null> {
    try {
      return await this.service.deleteApplicationUser({
        where: params,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,

          oAuth: {
            select: {
              id: true,
            },
          },

          password: true,

          role: {
            select: {
              id: true,
            },
          },

          supertokensId: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
